In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
#vectors
l=[[1,2,3],[4,5,6],[7,8,9]]
arr_l = np.array(l)
print(arr_l)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr = np.arange(1,11,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [9]:
np.random.rand(10)

array([0.38085385, 0.41263386, 0.67107742, 0.53666001, 0.9256969 ,
       0.04136831, 0.27491372, 0.17027654, 0.52999264, 0.99400243])

In [10]:
np.random.randn(10)

array([ 0.35639054, -1.86158736, -0.29331778,  1.00692835,  0.47232091,
       -0.50079135,  0.65412714, -0.35092402, -0.646547  , -0.73730576])

In [11]:
np.random.randint(10,20,10)

array([14, 10, 15, 12, 17, 15, 18, 18, 17, 16])

In [13]:
arr.shape
arr.size

100

In [15]:
arr.min()
arr.max()

np.float64(1.0)

In [18]:
np.sum(arr,axis=0)

np.float64(50.0)

In [19]:
arr.mean()

np.float64(0.5)

In [20]:
arr.std()

np.float64(0.29157646512850627)

In [21]:
arr.argmax()

np.int64(99)

In [22]:
arr.argmin()

np.int64(0)

In [27]:
arr = np.arange(1,31)
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])