In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [ ]:
array_addition = a1+a2
array_addition



array([0.25, 0.4 , 0.5 ])

In [6]:
array_subtraction = a1-a2
array_subtraction


array([-3, -3, -3])

In [7]:
array_multiplication = a1*a2
array_multiplication

array([ 4, 10, 18])

In [8]:
array_division = a1/a2
array_division

array([0.25, 0.4 , 0.5 ])

In [11]:
array_broadcasting = np.array([1,2,3])
broadcasting_result = array_broadcasting*10
broadcasting_result

array([10, 20, 30])

In [13]:
arr =np.arange(1,26).reshape(5,5)
arr+10


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [15]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
a_slice = a[:5]
a_slice = a*10
a_slice
b_slice = a_slice.copy()
b_slice[0] = 99
b_slice

array([ 99,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])

In [27]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [ ]:
A = mat1 @ mat2 # or np.dot(mat1, mat2)
A

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [30]:
A.T

array([[ 30,  84, 138],
       [ 24,  69, 114],
       [ 18,  54,  90]])

In [32]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [33]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [39]:
c = np.arange(16).reshape(4,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [40]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [44]:
a =  np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [45]:
import numpy as np

# Create an array with shape (3, 1, 4)
my_array = np.zeros((3, 1, 4)) # Or np.arange(12).reshape(3, 1, 4)

print(my_array.shape) # Output: (3, 1, 4)
print(my_array)


(3, 1, 4)
[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]


In [47]:
your_array = np.zeros((1,5,4))
print(your_array)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [50]:
summation = my_array+your_array
summation.shape

(3, 5, 4)