In [1]:
import numpy as np 
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [4]:
b = np.sum(s,axis=1)
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("Sudoku row is valid")

Sudoku row is valid


In [6]:
c = np.sum(s,axis=0)
for i in c:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("Sudoku col is valid")

Sudoku col is valid


In [7]:
data = np.array([
    [18,85,78],
    [19,92,98],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [8]:
data.shape

(5, 3)

In [13]:
ages = data[0::,0]
average_age = ages.mean()
print(average_age)

18.4


In [16]:
math_marks = data[0::,1]
math_marks

array([85, 92, 76, 65, 90])

In [19]:
science_marks = data[0::,2]
highest_science_marks = science_marks.max()
print(highest_science_marks)

98


In [22]:
math_marks_idx = np.where(math_marks > 90)
highest_scored_student = data[math_marks_idx]
print(highest_scored_student)

[[19 92 98]]


In [24]:
updated_math_marks = math_marks + 5
updated_math_marks

array([90, 97, 81, 70, 95])

In [27]:
elder_students = ages[ages > 19]
elder_students


array([20])

In [29]:
math_avg = math_marks.mean()
math_avg

np.float64(81.6)

In [32]:
science_avg = science_marks.mean()