In [1]:
import numpy as np

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
array_slice =arr[3:9]

In [4]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [13]:
arr_slice =arr[0:2,1:3]
arr_slice

array([[2, 3],
       [7, 8]])

In [17]:
arr_slice1 = arr[3::,3::]
arr_slice1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [18]:
arr2 = np.arange(11,21)
arr2 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
bool_index = arr2 % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [23]:
arr2 = arr2[bool_index]
arr2

array([12, 14, 16, 18, 20])