The Moving Average

In [15]:
import numpy as np
k = int(input("Enter number of slices you want"))
n = int(input("Enter length of array ?"))
array_1 = np.arange(n)
window_sum = np.sum([array_1[i:i+n-k+1] for i in range(k)],axis=0)
moving_avg = window_sum / k
print(moving_avg[:10])


[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


The Nearest Neighbor

In [24]:
landmarks = np.random.randn(10,3)
robot_pos = np.random.randn(3)

the_nearest_neighbour = landmarks - robot_pos
squared_difference = np.square(the_nearest_neighbour)
distances_sq = np.sum(squared_difference, axis=1)
closest_index = np.argmin(distances_sq)

print(f"The closest landmark is at index: {closest_index}")
print(f"The distance is: {np.sqrt(distances_sq[closest_index])}")

The closest landmark is at index: 0
The distance is: 0.765645744460139


Image Masking

In [31]:
img = np.random.randint(0, 255, (256, 256, 3))
red_channel = img[:, :, 0]
mask = red_channel > 200
img[mask] = [0,0,225]
print(img)


[[[  0   0 225]
  [ 85 156  78]
  [152  26 210]
  ...
  [  2  67  63]
  [187 139  16]
  [ 55 161 213]]

 [[  0   0 225]
  [ 61 119  63]
  [ 74  21 141]
  ...
  [126 108 195]
  [200 119  24]
  [  0   0 225]]

 [[162 226  37]
  [200   7  68]
  [  0   0 225]
  ...
  [ 93 185 136]
  [  0   0 225]
  [117 206  60]]

 ...

 [[  0   0 225]
  [ 41 170 146]
  [  0   0 225]
  ...
  [ 68   5 107]
  [  3  78  96]
  [164  41 211]]

 [[ 13 127 210]
  [ 28 116  50]
  [  0   0 225]
  ...
  [169  55 237]
  [200  15 142]
  [156 205 180]]

 [[ 16 141 115]
  [  0   0 225]
  [117 168 152]
  ...
  [  0   0 225]
  [108  24  60]
  [  0   0 225]]]
